nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled
    - ./etc/nginx/conf:/etc/nginx/conf
    - ./www:/etc/nginx/html
  links:
    - php
  log_driver: "json-file"
  log_opt:
    max-size: "16k"
    max-file: "2"

php:
  build: .
  dockerfile: /etc/docker/dockerfile_php_7
  volumes:
    - ./www:/var/www/html
    - ./etc/php:/usr/local/etc/php
  links:
    - mysql
  log_driver: "json-file"
  log_opt:
    max-size: "16k"
    max-file: "2"

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=SECRET
  volumes:
    - ./etc/mysql:/docker-entrypoint-initdb.d
  log_driver: "json-file"
  log_opt:
    max-size: "16k"
    max-file: "2"