FROM php:7.0-fpm

RUN apt-get update

# Install mysqli
RUN docker-php-ext-install mysqli

# Install mcrypt
RUN apt-get install -y libmcrypt-dev
RUN docker-php-ext-install mcrypt

# Install gd
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng12-dev

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/

RUN docker-php-ext-install gd


# Install zip
RUN docker-php-ext-install zip

# RUN apt-get install libssl-dev -y


# We need to do something with the internal IP address that can be obtained via runing `php -i | grep 'MYSQL_PORT_3306_TCP_ADDR'` from within the php container.

# This address is critical for the setup process


CMD ["php-fpm"]