FROM php:7.0.2-fpm

RUN /usr/local/bin/docker-php-ext-install mysqli
RUN apt-get update
RUN apt-get install libssl-dev -y
RUN pecl install mongodb

RUN sed -i 's/pm.max_children = 5/pm.max_children = 10/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.start_servers = 2/pm.start_servers = 3/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.min_spare_servers = 1/pm.min_spare_servers = 3/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.max_spare_servers = 3/pm.max_spare_servers = 5/g' /usr/local/etc/php-fpm.d/www.conf

CMD ["php-fpm"]